# Generated by Django 4.0.4 on 2022-06-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_remove_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
    ]
